tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'htop'
brew 'rbenv'
brew 'ruby-build'
berw 'rmtrash'
brew 'the_silver_searcher'
brew 'direnv'
brew 'lua'
brew 'tig'
brew 'nodenv'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'curl'
brew 'vim'
brew 'zsh'
